pipeline {
   agent any
   tools{
	maven 'Maven 3.6.3'
   }
   
   stages {
        stage('build') {
            steps {
                echo 'compiling Worker App'
                dir('worker'){
		   sh 'mvn compile'
		}
            }
        }
        stage('test') {
            steps {
                echo 'Running unit tests on worker App'
		dir('worker'){
		   sh 'mvn clean test'
		}
            }
        }
        stage('package') {
            steps {
                echo 'Packaging Worker App'
            }
	    dir('worker'){
		   sh 'mvn package'
	    }
        }
    }
    post {
        always {
            echo 'the pipeline step is completed succesfully'
        }
    }
}
