pipeline {
   agent any
   tools{
	maven 'Maven 3.6.3'
   }
   
   stages {
        stage('build') {
	    when{
	     changeset "**/worker/**"
	    }
            steps {
                echo 'compiling Worker App'
                dir('worker'){
		   sh 'mvn compile'
		}
            }
        }
        stage('test') {
	    when{
	     changeset "**/worker/**"
	    }
            steps {
                echo 'Running unit tests on worker App'
		    dir('worker'){
		    	sh 'mvn clean test'
		    }
            }
        }
        stage('package') {
	    when{
	     branch 'master'
	     changeset "**/worker/**"
	    }
            steps {
                echo 'Packaging Worker App'
		dir('worker'){
		    	sh 'mvn package -DskipTests'
		}
            }
        }
    } 

    post {
        always {
	    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'the pipeline step is completed succesfully .... '
        }
    }
}
